# Generated by Django 2.2.7 on 2019-11-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('STALLED', 'Stalled')], default='Active')),
                ('ts_create', models.DateTimeField(auto_now_add=True)),
                ('ts_last', models.DateTimeField(auto_now=True)),
                ('ts_received', models.DateTimeField(blank=True)),
                ('relays', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('secret_pin', models.IntegerField(blank=True, null=True)),
                ('public_pin', models.IntegerField(blank=True, null=True)),
                ('centrality', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relay_destination', to='msggame.Person')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msggame.Message')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relay_source', to='msggame.Person')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='current_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_messages', to='msggame.Person'),
        ),
        migrations.AddField(
            model_name='message',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_origins', to='msggame.Person'),
        ),
        migrations.AddField(
            model_name='message',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_targets', to='msggame.Person'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField()),
                ('ts_create', models.DateTimeField(auto_now_add=True)),
                ('ts_used', models.DateTimeField(auto_now=True)),
                ('nuses', models.IntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_destinations', to='msggame.Person')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_sources', to='msggame.Person')),
            ],
        ),
    ]
