# Generated by Django 2.2.7 on 2019-11-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msggame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ts_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='ts_last',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='ts_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
