# Generated by Django 2.2.7 on 2019-11-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msggame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='pin',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='secret_pin',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['source', 'destination'], name='msggame_lin_source__633770_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['origin', 'target'], name='msggame_mes_origin__683665_idx'),
        ),
        migrations.AddIndex(
            model_name='relay',
            index=models.Index(fields=['source', 'destination'], name='msggame_rel_source__39e266_idx'),
        ),
    ]
