# Generated by Django 2.2.7 on 2019-11-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msggame', '0002_auto_20191117_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
