# Generated by Django 2.2.7 on 2019-11-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msggame', '0004_auto_20191117_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField(unique=True)),
                ('max_links', models.IntegerField(default=10)),
                ('allow_new_links', models.BooleanField(default=True)),
                ('disallow_existing_links', models.BooleanField(default=False)),
                ('require_links', models.BooleanField(default=False)),
                ('links_from_relays', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='path',
            new_name='path_ids',
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
