# Generated by Django 2.2.7 on 2019-11-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msggame', '0006_auto_20191117_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='consent_research',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='consent_research_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='consent_research_withname',
            field=models.BooleanField(default=False),
        ),
    ]
