# Generated by Django 2.2.7 on 2019-11-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msggame', '0007_auto_20191117_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ts_lastactive',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
